name: Run tests

on:
  # On main branch
  push:
   branches:
     - 'main'
  # trigger or event
  pull_request:
  # when the extraction resquest is initiated or opened
    type:
      - opened
  # On main branch
    branches:
      - 'main'
  # Before to modified all file.py
    paths:
      - '*.py'
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - name: Update packages
        run: sudo apt update
      - name: Launch installation ycodestyle
        run: sudo apt install -y pycodestyle
      - name: Check code
        run: pycodestyle --first *.py
      - name: Message
        run: echo "Check Success !"

